/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.base;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int buttonSize = 0x7f020041;
        public static final int circleCrop = 0x7f02004f;
        public static final int colorScheme = 0x7f02005e;
        public static final int imageAspectRatio = 0x7f020093;
        public static final int imageAspectRatioAdjust = 0x7f020094;
        public static final int scopeUris = 0x7f0200d2;
    }
    public static final class color {
        private color() {}

        public static final int common_google_signin_btn_text_dark = 0x7f040029;
        public static final int common_google_signin_btn_text_dark_default = 0x7f04002a;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f04002b;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f04002c;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f04002d;
        public static final int common_google_signin_btn_text_light = 0x7f04002e;
        public static final int common_google_signin_btn_text_light_default = 0x7f04002f;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f040030;
        public static final int common_google_signin_btn_text_light_focused = 0x7f040031;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f040032;
        public static final int common_google_signin_btn_tint = 0x7f040033;
    }
    public static final class drawable {
        private drawable() {}

        public static final int common_full_open_on_phone = 0x7f060055;
        public static final int common_google_signin_btn_icon_dark = 0x7f060056;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f060057;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f060058;
        public static final int common_google_signin_btn_icon_dark_normal_background = 0x7f